### ISSUE TITLE
Deeply nested objects don't get parsed correctly

### ISSUE THREAD

**Issue by criles25** [victorteokw/query-string-parser#1]
E.g., this object doesn't get parsed by Rack correctly

```
{ 
  filters: [ 
    { estimated_hours: { greater_than_or_equal_to: 2, less_than_or_equal_to: 10 } }, 
    { is_busy: false } 
  ]
}
```

**Comment by victorteokw** [comment]
Hi @criles25, this is the correct behavior. 

By design, rack works this way.

Rack will not trying to convert 2 to number, and query-string-parser behaves the same with rack.
